name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.3.1

      - name: Install dependencies
        run: pnpm install

      - name: Envfile
        run: echo "BASE_PATH='/ufv-today'" > .env

      - name: Build project
        env:
          BASE_PATH: '/ufv-today'
        run: npm run build; touch build/.nojekyll pnpm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./build
      - name: Deploy to pages
        id: deployment
        uses: actions/deploy-pages@v2